### ISSUE TITLE
Disabling completly a package need window.reload

### ISSUE THREAD

**Issue by seksenbes85** [robenkleene/toggle-packages#7] opened 2016-11-12 14:27 UTC
Hi,

toggle-packages does not works as expected. It needs windows.reload method. I had open here a post for this issue. I would be happy if you can help.

https://discuss.atom.io/t/disabling-package-from-command-pallet

Thank you

**Comment by robenkleene** [comment] 2016-11-12 22:45
Thanks for the report, I think I've confirmed that you are right, disabled packages seem to leave some remains behind. I'm going to try and put together a fix. Cheers,
-Roben

**Comment by robenkleene** [comment] 2016-11-18 03:16
I took another look at this and it appears that this is not a Toggle Packages bug. If I disable a package via Atom's UI, without using Toggle Packages at all, it will also leave behind commands for the disabled package in the command palette. I'm closing this as a bug, because Toggle Packages is intended just as another UI for Atom's built-in disable packages functionality -- but with that said I agree it's really weird that disabled packages still list there commands in the command palette.

**Closed as completed by robenkleene** 2016-11-18 03:16 UTC
